# Generated by Django 3.2.8 on 2021-11-09 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answer_domain_question_questionstags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('correct_option', models.CharField(max_length=1000)),
                ('submitted_time', models.TimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ques', to='app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['id'],
            },
        ),
    ]
