# Generated by Django 3.2.8 on 2021-11-10 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211109_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(max_length=100, verbose_name='Registration Number'),
        ),
    ]
