# Generated by Django 3.2.8 on 2021-11-11 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_reg_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
