# Generated by Django 3.2.8 on 2021-11-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.domain'),
        ),
        migrations.AlterField(
            model_name='questionstags',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
