# Generated by Django 3.2.8 on 2021-11-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_submission_ques_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='domain',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='sub_domain', to='app.domain'),
        ),
    ]
