# Generated by Django 3.2.8 on 2021-11-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_submission_mark_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mark_ques',
            field=models.IntegerField(),
        ),
    ]
