# Generated by Django 3.2.8 on 2021-11-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_results_temp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='option',
        ),
    ]
