# Generated by Django 3.2.8 on 2021-11-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='option',
        ),
    ]
