# Generated by Django 3.2.8 on 2021-11-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_questionstags_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstags',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.question'),
        ),
    ]
