# Generated by Django 3.2.8 on 2022-02-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_questionstags_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_main',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
